[project]
name = "deepeval-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepeval>=3.6.7",
    "langchain==0.3.27",
    "langchain-openai==0.3.35",
    "langgraph==0.6.11",
]
